### PR TITLE
Some new functions and some fixes

### PR DESCRIPTION
**Pull request by MorningDemon515**
Added:
TextureBumpEnvMat,
TextureBumpEnvScale,
TextureBumpEnvOffset,
TextureLodBias

Among them,
TextureBumpEnvMat,
TextureBumpEnvScale,
TextureBumpEnvOffset,
These three functions can be used to achieve bump textures or bump mapping effects

The specific parameters are as follows:
TextureBumpEnvMat Texture, 0,0, -0.012
TextureBumpEnvMat Texture, 0,1, -0.012
TextureBumpEnvMat Texture, 1,0,0.012
TextureBumpEnvMat Texture, 1,1,0.012
TextureBumpEnvOffset Texture, 0.5
TextureBumpEnvScale Texture, 1.0

TextureLodBias:
TextureFloat #=0.8
TextureLodBias TextureFloat

Just add it to the code, you can change 0.8 to another number
Updated development tools to MSVC_2019 and corrected README.md

### CODE REVIEW

**Comment by blitz-research** [comment]
Hi,

Wow, lots of good looking stuff in there, a few issues though:

* Can you add some docs for new b3d texture commands to _release/help? Doesn't have to be anything major, just a one liner would be OK but the more the better of course!

* Can you add cmake support for freetype? I recently added cmake builds and this will be the recommended way of building going forward.

* I could build OK with VS2022 but couldn't run the 'castle' or 'dragon' samples - the runtime window just opens and then immediately closes. The 'dolphin' demo ran OK though. Note these were the only samples I tried.

*  I'm not sure if upgrading to VS2019 achieves a lot when a lot of people will be running 2022, eg: I still had to 'retarget solution'. I think drop these changes and lets stick with cmake as primary build tool. Although I guess adding freetype to the VS project would then require you to be running VS2017...kind of tempted to just drop the VS project altogether and go cmake only.

All-in-all, I think I'd rather see this split into smaller PR's, perhaps one for the new commands/docs, and a separate one for freetype?

Bye!
Mark

**Comment by blitz-research** [comment]
For unicode font support, did you consider using the wide char version of the windows system calls that are already in there, eg: using GetTextExtentPoint32W and GetCharABCWidthsW in createFont here:

https://github.com/blitz-research/blitz3d_msvc2017/blob/f7e5643197faab96befb0e4aa415781c66f67b6a/gxruntime/gxgraphics.cpp#L233

It should at least be possible to generate gxFont's with more that 256 chars this way. That said, I have no idea how good it'd look. The existing code doesn't look like it does anything with kerning etc, although surely that vould be fairly easily added?

Dunno, freetype's kind of a beast (a friendly one though!) and I'm sort of reluctant to just throw it in there if there's an existing way to do it. Although I do see it's gonna be necessary to 'fix' fonts one way or the other if we really want to support utf8.

**Comment by MorningDemon515** [comment]
I think I will do everything in my power to complete it

**Comment by blitz-research** [comment]
I'm not happy with the freetype addition as is, it should be possible to reduce the number of extra files massivley, either by implementing a simpler Win32 solution as above, or at the very least stripping out redundant files from free type.

There is also stb_truetype which I had completely forgotten about:  https://github.com/nothings/stb/blob/master/stb_truetype.h I used this for Encounter and it works just as well as freetype but is a single file! You wouldn't even have to add a new project.

> Font=LoadFont ("verdana", 16)
> It is illegal and needs to be changed from "verdana" to "C: \ Windows \ Fonts \ verdana. ttf"

This isn't very user friendly IMO, it would break a lot of existing code. It shouldn't be hard to make this backward compatible, LoadFont should try current dir first, and if that fails then try windows font dir.

Please make another PR for *just* the new commands (with new _release/help docs!) for now, I'll have to think about the freetype stuff.

**Comment by MorningDemon515** [comment]
I have deleted a lot of freetype files, leaving only include and lib files to alleviate some of the burden. I have also added UTF8 support for debuggers and fixed some font function issues. It will take some time to add the freetype cmakelist file and the release/help file



-2024/3/2
-Morning Demon

**Comment by MorningDemon515** [comment]
I have added an HTML file for the new function

**Comment by MorningDemon515** [comment]
CMakeLisis.txt for freetype

**Comment by MorningDemon515** [comment]
I have decided to restore the code to its original state and make modifications from scratch

**Comment by MorningDemon515** [comment]
So this pull request can be closed now

**Pull request closed without merging**
